# coding=utf-8

from MedicalExamPart1 import MedicalExamPart1
from django.db import models
from django.forms import ModelForm
from django.forms import RadioSelect

class MedicalExamPart1Form(ModelForm):
    class Meta:
        model = MedicalExamPart1
        fields = (
            'date',
            'background_notes',
            'birth_history',
            'bcg_vaccine',
            'bcg_vaccine_date',
            'polio_vaccine',
            'polio_vaccine_date',
            'dpt_vaccine',
            'dpt_vaccine_date',
            'hepatitis_b_vaccine',
            'hepatitis_b_vaccine_date',
            'flu_vaccine',
            'flu_vaccine_date',
            'yellow_fever_vaccine',
            'yellow_fever_vaccine_date',
            'spr_vaccine',
            'spr_vaccine_date',
            'hpv_vaccine',
            'hpv_vaccine_date',
            'pneumococcal_vaccine',
            'pneumococcal_vaccine_date',
            'weight',
            'height',
            'hemoglobin_normal',
            'hemoglobin_notes',
            'elisa_vh1_positive',
            'hepatitisB_positive',
            'PPD_positive',
            'stool_parasites_positive',
            'stool_parasites_notes',
            'leukocytes_normal',
            'leukocytes_notes',
            'nitrites_normal',
            'nitrites_notes',
            'urobilinogen_normal',
            'urobilinogen_notes',
            'protein_normal',
            'protein_notes',
            'pH_normal',
            'pH_notes',
            'hemoglobin_normal',
            'hemoglobin_notes',
            'density_normal',
            'density_notes',
            'glucose_normal',
            'glucose_notes',
        )
        labels = {
            'date': 'Fecha',
            'background_notes': 'Antecedents Familiares Patológicos y de Riesgo Conocidos',
            'birth_history': 'Historia Perinatal y Neonatal',
            'bcg_vaccine': 'BCG',
            'bcg_vaccine_date': 'Fecha de Administracion',
            'polio_vaccine': 'Antipoliomielitica',
            'polio_vaccine_date': 'Fecha de Administracion',
            'dpt_vaccine': 'DPT',
            'dpt_vaccine_date': 'Fecha de Administracion',
            'hepatitis_b_vaccine': 'Hepatitis B',
            'hepatitis_b_vaccine_date': 'Fecha de Administracion',
            'flu_vaccine': 'Hemofilus Influenza',
            'flu_vaccine_date': 'Fecha de Administracion',
            'yellow_fever_vaccine': 'Fiebre Amarilla',
            'yellow_fever_vaccine_date': 'Fecha de Administracion',
            'spr_vaccine': 'SPR',
            'spr_vaccine_date': 'Fecha de Administracion',
            'hpv_vaccine': 'HPV',
            'hpv_vaccine_date': 'Fecha de Administracion',
            'pneumococcal_vaccine': 'Neumococo',
            'pneumococcal_vaccine_date': 'Fecha de Administracion',
            'weight': 'Peso',
            'height': 'Estatura',
            'hemoglobin_normal': 'Hemoglobina',
            'hemoglobin_notes': 'Comentarios',
            'elisa_vh1_positive': 'Elisa VH1',
            'hepatitisB_positive': 'Hepatitis B',
            'PPD_positive': 'PPD',
            'stool_parasites_positive': 'Parasitos Heces',
            'stool_parasites_notes': 'Lista si es positivo',
            'leukocytes_normal': 'Leucocitos',
            'leukocytes_notes': 'Comentarios',
            'nitrites_normal': 'Nitritos',
            'nitrites_notes': 'Comentarios',
            'urobilinogen_normal': 'Urobilinógeno',
            'urobilinogen_notes': 'Comentarios',
            'protein_normal': 'Proteína',
            'protein_notes': 'Comentarios',
            'pH_normal': 'pH',
            'pH_notes': 'Comentarios',
            'density_normal': 'Densidad',
            'density_notes': 'Comentarios',
            'glucose_normal': 'Glucosa',
            'glucose_notes': 'Comentarios',
        }
        widgets = {
            'bcg_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'polio_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'dpt_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'hepatitis_b_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'flu_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'yellow_fever_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'spr_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'hpv_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'pneumococcal_vaccine': RadioSelect(choices=((True, 'Si'),(False, 'No'))),
            'hemoglobin_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'elisa_vh1_positive': RadioSelect(choices=((True, 'Positivo'),(False, 'Negativo'))),
            'hepatitisB_positive': RadioSelect(choices=((True, 'Positivo'),(False, 'Negativo'))),
            'PPD_positive': RadioSelect(choices=((True, 'Positivo'),(False, 'Negativo'))),
            'stool_parasites_positive': RadioSelect(choices=((True, 'Positivo'),(False, 'Negativo'))),
            'leukocytes_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'nitrites_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'urobilinogen_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'protein_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'pH_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'hemoglobin_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'density_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
            'glucose_normal': RadioSelect(choices=((True, 'Normal'),(False, 'Anormal'))),
        }
