# coding=utf-8

from MedicalExamPart1 import MedicalExamPart1
from django.db import models
from django.forms import ModelForm

class MedicalExamPart1Form(ModelForm):
    class Meta:
        model = MedicalExamPart1
        fields = {
            'date',
            'background_notes',
            'birth_history',
            'bcg_vaccine',
            'bcg_vaccine_date',
            'polio_vaccine',
            'polio_vaccine_date',
            'dpt_vaccine',
            'dpt_vaccine_date',
            'hepatitis_b_vaccine',
            'hepatitis_b_vaccine_date',
            'flu_vaccine',
            'flu_vaccine_date',
            'yellow_fever_vaccine',
            'yellow_fever_vaccine_date',
            'spr_vaccine',
            'spr_vaccine_date',
            'hpv_vaccine',
            'hpv_vaccine_date',
            'pneumococcal_vaccine',
            'pneumococcal_vaccine_date',
            'weight',
            'height',
            'hemoglobin_normal',
            'hemoglobin_notes',
            'elisa_vh1_positive',
            'hepatitisB_positive',
            'PPD_positive',
            'stool_parasites_positive',
            'stool_parasites_notes',
            'leukocytes_normal',
            'leukocytes_notes',
            'nitrites_normal',
            'nitrites_notes',
            'urobilinogen_normal',
            'urobilinogen_notes',
            'protein_normal',
            'protein_notes',
            'pH_normal',
            'pH_notes',
            'hemoglobin_normal',
            'hemoglobin_notes',
            'density_normal',
            'density_notes',
            'glucose_normal',
            'glucose_notes',
        }
        labels = {
            'date': 'Fecha',
            'background_notes': 'Antecedents Familiares Patológicos y de Riesgo Conocidos',
            'birth_history': 'Historia Perinatal y Neonatal',
            'bcg_vaccine': 'BCG; Si/No',
            'bcg_vaccine_date': 'Fecha de Administracion',
            'polio_vaccine': 'Antipoliomielitica; Si/No',
            'polio_vaccine_date': 'Fecha de Administracion',
            'dpt_vaccine': 'DPT; Si/No',
            'dpt_vaccine_date': 'Fecha de Administracion',
            'hepatitis_b_vaccine': 'Hepatitis B; Si/No',
            'hepatitis_b_vaccine_date': 'Fecha de Administracion',
            'flu_vaccine': 'Hemofilus Influenza; Si/No',
            'flu_vaccine_date': 'Fecha de Administracion',
            'yellow_fever_vaccine': 'Fiebre Amarilla; Si/No',
            'yellow_fever_vaccine_date': 'Fecha de Administracion',
            'spr_vaccine': 'SPR; Si/No',
            'spr_vaccine_date': 'Fecha de Administracion',
            'hpv_vaccine': 'HPV; Si/No',
            'hpv_vaccine_date': 'Fecha de Administracion',
            'pneumococcal_vaccine': 'Neumococo; Si/No',
            'pneumococcal_vaccine_date': 'Fecha de Administracion',
            'weight': 'Peso',
            'height': 'Estatura',
            'hemoglobin_normal': 'Normal/Anormal',
            'hemoglobin_notes': 'Hemoglobina',
            'elisa_vh1_positive': 'Elisa VH1  Positivo/Negativo',
            'hepatitisB_positive': 'Hepatitis B Positivo/Negativo',
            'PPD_positive': 'PPD Positivo/Negativo',
            'stool_parasites_positive': 'Positivo/Negativo',
            'stool_parasites_notes': 'Parasitos Heces (lista si es positivo)',
            'leukocytes_normal': 'Normal/Anormal',
            'leukocytes_notes': 'Leucocitos',
            'nitrites_normal': 'Normal/Anormal',
            'nitrites_notes': 'Nitritos',
            'urobilinogen_normal': 'Normal/Anormal',
            'urobilinogen_notes': 'Urobilinógeno',
            'protein_normal': 'Normal/Anormal',
            'protein_notes': 'Proteína',
            'pH_normal': 'Normal/Anormal',
            'pH_notes': 'pH',
            'hemoglobin_normal': 'Normal/Anormal',
            'hemoglobin_notes': 'Hemoblobina',
            'density_normal': 'Normal/Anormal',
            'density_notes': 'Densidad',
            'glucose_normal': 'Normal/Anormal',
            'glucose_notes': 'Glucosa',
        }
